### PR TITLE
cli: add --dest, --symlink and --hardlink flags

### LINKED ISSUE #7: Symlink support?
would there be interest in adding symlink support? I personally prefer this approach to library management, and have changed `std::fs::rename` to `std::os::unix::fs::symlink` for my own use. I understand symlinks would need to be implemented os-agnostic to support windows.

Let me know if you would like a PR and I can try to add windows support for symlinking and a proper cli option

### PR DESCRIPTION
**Pull request by BurntSushi**
The --dest flag permits control over where files are renamed or linked
to.

The --symlink flag causes imdb-rename to symlink media files instead of
renaming them. Similarly, the --hardlink flag causes imdb-rename to
hardlink media files instead of renaming them.

Hardlinking doesn't work with directories and symlinks aren't
supported on Windows.

Fixes #7, Closes #14

cc @evanrichter - I did some minor cleanup work on your PR. There were still a few formatting issues. I'll be switching to rustfmt soon, so hopefully that won't be a big issue in the future.

### CODE REVIEW

**Comment by ImportTaste** [comment]
I'm interested in this feature. Could you do a new release?

**Comment by evanrichter** [comment]
I honestly kind of regret adding this complexity to the tool. In hindsight, I was too narrow focused on making imdb-rename do too much in my workflow.

I think a simple command suffices as a replacement for this feature:
```bash
ln -s target_dir src_filename        # create link
imdb-rename target_dir/src_filename  # rename the link in place
```
You can easily do hardlinks if your platform supports it too.

Adding 3 cli args and 200 lines of rust was probably not worth it!

I'm curious if you still think you need this in the next release.

**Comment by ImportTaste** [comment]
I can't say I truly need it, it was just a matter of convenience. It's disappointing, but ultimately it's your project.

**Comment by BurntSushi** [comment]
I have no idea when I'm going to do a release. I don't know that I ever will. I suggest just installing it with Cargo. You can use the `--git` flag on `cargo install` to point it to latest master.

**Comment by BurntSushi** [comment]
`cargo install --git https://github.com/BurntSushi/imdb-rename`

**Comment by ImportTaste** [comment]
> `cargo install --git https://github.com/BurntSushi/imdb-rename`

Hum. It fails with this output: `error: multiple packages with binaries found: imdb-eval, imdb-rename`

**Comment by BurntSushi** [comment]
`cargo install --help` should help you here. Try `cargo install --git https://github.com/BurntSushi/imdb-rename --bin imdb-rename`.

**Comment by ImportTaste** [comment]
> `cargo install --help` should help you here. Try `cargo install --git https://github.com/BurntSushi/imdb-rename --bin imdb-rename`.

Same error, strangely enough. I've tried
```
cargo install --bin imdb-rename --git https://github.com/BurntSushi/imdb-rename
cargo install --git https://github.com/BurntSushi/imdb-rename --bin imdb-rename
cargo install --bins --git https://github.com/BurntSushi/imdb-rename
cargo install --git https://github.com/BurntSushi/imdb-rename --bins
```
But I always get `error: multiple packages with binaries found: imdb-eval, imdb-rename`

**Comment by BurntSushi** [comment]
Well that's... odd... OK, so I actually ran these commands and it works:

```
$ cd /tmp/
$ git clone https://github.com/BurntSushi/imdb-rename
$ cd imdb-rename/
$ cargo install --path .
$ which imdb-rename
/home/andrew/.local/cargo/bin/imdb-rename
```

**Comment by ImportTaste** [comment]
> Well that's... odd... OK, so I actually ran these commands and it works:
> 
> ```
> $ cd /tmp/
> $ git clone https://github.com/BurntSushi/imdb-rename
> $ cd imdb-rename/
> $ cargo install --path .
> $ which imdb-rename
> /home/andrew/.local/cargo/bin/imdb-rename
> ```

Well, that seemed to be working, until it got to this part:

```
error[E0658]: use of unstable library feature 'matches_macro'
   --> C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\rustc-demangle-0.1.21\src\v0.rs:700:20
    |
700 |                 if matches!((quote, c), ('\'', '"') | ('"', '\'')) {
    |                    ^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/65721

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `rustc-demangle`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `imdb-rename v0.1.5 (C:\tmp\imdb-rename)`, intermediate artifacts can be found at `C:\tmp\imdb-rename\target`

Caused by:
  build failed
```

**Comment by BurntSushi** [comment]
OK, well, that is at least something I understand. It's almost certain that you're trying to build with an older version of Rust. Please upgrade to a newer version. If you're using a Linux distribution that only provides old software to you, then you'll want to install rustup and use the latest version of Rust.

**Comment by BurntSushi** [comment]
Also, this is the `cargo install` command that works: `cargo install --git https://github.com/BurntSushi/imdb-rename imdb-rename`

But you still need a more recent version of Rust to build `imdb-rename`.

**Comment by ImportTaste** [comment]
> OK, well, that is at least something I understand. It's almost certain that you're trying to build with an older version of Rust. Please upgrade to a newer version. If you're using a Linux distribution that only provides old software to you, then you'll want to install rustup and use the latest version of Rust.

> Also, this is the `cargo install` command that works: `cargo install --git https://github.com/BurntSushi/imdb-rename imdb-rename`
> 
> But you still need a more recent version of Rust to build `imdb-rename`.

There we go, sorry about that. I thought I had Chocolatey maintaining it automatically, but it turns out I had to run `rustup update`. It's been around a couple years since I last compiled a rust project.

It worked well, thank you.

**Pull request merged**
