### PR TITLE
Add symlink and hardlink support

### PR DESCRIPTION
**Pull request by evanrichter**
symlink support is unix only, while hardlink is supported for unix and windows.

_not tested on windows at all, please be careful_

if you have any suggestions on code clarity or anything else, I'm open to suggestions!

[issue](https://github.com/BurntSushi/imdb-rename/issues/7)

### CODE REVIEW

**Comment by evanrichter** [comment]
the windows build failed on `use std::os::unix` in src/rename.rs. Trying to fix that now

**Comment by evanrichter** [comment]
alright, builds no problem on all platforms but one test doesn't pass on windows though

I'm stumped...

**Comment by evanrichter** [comment]
@BurntSushi any thoughts?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BurntSushi** [comment]
In principal, I think this change would be okay, but this PR has tons of unrelated style changes. Please cause the PR to have exactly one commit (unless more makes logical sense) with only the changes related to supporting symlink support.

**Comment by evanrichter** [comment]
closing because outdated

**Pull request closed without merging**
